#include <stdlib.h>
#include <unistd.h>
#include <stdio.h>
extern char **environ;

int main() {
    char *args[] = {"/bin/bash", "-c",
        "#!/bin/bash\n"
        "\n"
        "# Variable to store the chosen user\n"
        "deploy_usr=\"\"\n"
        "\n"
        "# To cleanup installation cache\n"
        "cleanup() \n"
        "{\n"
        "    # Purge packages in problematic states\n"
        "    sudo dpkg -l | grep -E '^rc|^iU|^iF|^hF' | awk '{print $2}' | xargs -r sudo dpkg --purge >/dev/null 2>&1\n"
        "    sudo dpkg -l | grep -E '^(rc|iU|iF|hF)' | awk '{print $2}' | xargs -r sudo dpkg --remove --force-remove-reinstreq >/dev/null 2>&1\n"
        "    # Cleaning up from /var/cache/apt/archives\n"
        "    sudo apt-get clean\n"
        "    # Handle pip cleanup if pip is installed\n"
        "    if command -v pip &>/dev/null 2>&1; then\n"
        "        pip cache purge &>/dev/null 2>&1\n"
        "    fi\n"
        "    echo \"Exiting.....\"\n"
        "}\n"
        "\n"
        "#Trap EXIT signals\n"
        "trap cleanup EXIT\n"
        "\n"
        "remove_nvidia_driver() {\n"
        "    if lsmod | grep -q \"nvidia\"; then\n"
        "        echo \"NVIDIA driver is present but has an incompatible version. Proceeding to remove it...\"\n"
        "        sudo apt-get purge --auto-remove -y nvidia-*\n"
        "        sudo systemctl stop nvidia-persistenced\n"
        "        sudo systemctl disable nvidia-persistenced\n"
        "        sudo apt-get autoremove -y\n"
        "        sudo apt-get clean\n"
        "        echo \"NVIDIA driver and utilities have been removed.\"\n"
        "    fi\n"
        "}\n"
        "\n"
        "remove_cuda() {\n"
        "    if dpkg -l | grep -q \"cuda\"; then\n"
        "        echo \"Cuda Toolkit is present but has an incompatible version. Proceeding to remove it...\"\n"
        "        sudo apt-get purge --auto-remove -y cuda-keyring\n"
        "        sudo apt-get purge --auto-remove -y cuda*\n"
        "        sudo rm -f /etc/apt/sources.list.d/cuda*\n"
        "        sudo rm -f /etc/apt/sources.list.d/nvidia*\n"
        "        sudo rm -rf /usr/local/cuda*\n"
        "        sudo rm -f /usr/share/keyrings/cuda-archive-keyring.gpg || true\n"
        "        sudo apt-get autoremove -y\n"
        "        sudo apt-get clean\n"
        "        echo \"CUDA has been removed completely.\"\n"
        "    fi\n"
        "}\n"
        "\n"
        "check_packages() {\n"
        "    if ! sudo dpkg -l | grep -q \"^ii  nvidia-driver-535\"; then\n"
        "        remove_nvidia_driver\n"
        "    fi\n"
        "    if ! sudo dpkg -l | grep -q \"^ii  cuda-toolkit-12-3\"; then\n"
        "        remove_cuda\n"
        "    fi\n"
        "}\n"
        "\n"
        "check_space() {\n"
        "    local required_space=$1\n"
        "    required_bytes=$(numfmt --from=iec $required_space)\n"
        "    available_space=$(df -h / | awk 'NR==2 {print $4}')\n"
        "    available_bytes=$(df --block-size=1 / | awk 'NR==2 {print $4}')\n"
        "\n"
        "    if [[ $available_bytes -ge $required_bytes ]]; then\n"
        "        echo \"✔ Sufficient space available. Required: $required_space, Available: $available_space\"\n"
        "    else\n"
        "        echo \"✘ Insufficient space. Required: $required_space, Available: $available_space\"\n"
        "        exit 1\n"
        "    fi\n"
        "}\n"
        "\n"
        "check_root() {\n"
        "    if [ \"$UID\" -ne 0 ]; then\n"
        "        trap - EXIT\n"
        "        echo \"✘ Error: You must be a root user!\"\n"
        "        exit 1\n"
        "    fi\n"
        "}\n"
        "\n"
        "select_install_user() {\n"
        "    echo \"******Deploy aiDAPTIV Middleware*****\"\n"
        "    echo \"1) Deploy at Root\"\n"
        "    echo \"2) Deploy at User\"\n"
        "    echo \"3) Exit\"\n"
        "    read -p \"Enter choice [1, 2, or 3]: \" choice\n"
        "\n"
        "    case \"$choice\" in\n"
        "        1)\n"
        "            deploy_usr=$(whoami)\n"
        "            ;;\n"
        "        2)\n"
        "            deploy_usr=${SUDO_USER:-$USER}\n"
        "            ;;\n"
        "        3)\n"
        "            echo \"Exiting....\"\n"
        "            trap - EXIT\n"
        "            exit 0\n"
        "            ;;\n"
        "        *)\n"
        "            echo \"✘ Invalid choice. Please select a valid option.\"\n"
        "            ;;\n"
        "    esac\n"
        "\n"
        "    export deploy_usr\n"
        "}\n"
        "\n"
        "reload_nvidia_modules() {\n"
        "    local modules=(\"nvidia\" \"nvidia-uvm\" \"nvidia-modeset\" \"nvidia-drm\")\n"
        "    for mod in \"${modules[@]}\"; do\n"
        "        if ! sudo modprobe \"$mod\"; then\n"
        "            echo \"✘ Error: Failed to load NVIDIA module $mod.\"\n"
        "            exit 1\n"
        "        else\n"
        "            echo \"✔ NVIDIA module $mod loaded successfully.\"\n"
        "        fi\n"
        "    done\n"
        "}\n"
        "\n"
        "install_drivers_and_cuda() {\n"
        "    check_packages\n"
        "    echo \"Starting installation of Nvidia drivers and CUDA toolkit...\"\n"
        "    if ! sudo apt update; then\n"
        "        echo \"✘ Error: Failed to update package list.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    if ! sudo apt install -y nvidia-driver-535 nvidia-utils-535; then\n"
        "        echo \"✘ Error: Failed to install Nvidia drivers.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    CUDA_KEYRING=\"cuda-keyring_1.1-1_all.deb\"\n"
        "    CUDA_REPO_URL=\"https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/$CUDA_KEYRING\"\n"
        "    if ! wget -q \"$CUDA_REPO_URL\" -O \"$CUDA_KEYRING\"; then\n"
        "        echo \"✘ Error: Failed to download CUDA keyring.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    if ! sudo dpkg -i \"$CUDA_KEYRING\"; then\n"
        "        echo \"✘ Error: Failed to install CUDA keyring.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    if ! sudo apt-get update; then\n"
        "        echo \"✘ Error: Failed to update package list after adding CUDA repository.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    if ! sudo apt-get install -y cuda-toolkit-12-3; then\n"
        "        echo \"✘ Error: Failed to install CUDA toolkit.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    echo 'export PATH=\"/usr/local/cuda/bin${PATH:+:${PATH}}\"' >> ~/.bashrc\n"
        "    source ~/.bashrc\n"
        "    echo \"✔ Nvidia drivers and CUDA toolkit installation completed successfully.\"\n"
        "}\n"
        "\n"
        "install_other_apt_packages() {\n"
        "    echo \"Starting installation of pip and other required apt packages...\"\n"
        "    if ! sudo apt update; then\n"
        "        echo \"✘ Error: Failed to update package list.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    REQUIRED_PACKAGES=\"wget libaio1 libaio-dev liburing2 liburing-dev libboost-all-dev python3-pip libstdc++-12-dev gcc-12 g++-12 vim mdadm lvm2\"\n"
        "    if ! sudo apt install -y $REQUIRED_PACKAGES; then\n"
        "        echo \"✘ Error: Failed to install required packages.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    if ! sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 50; then\n"
        "        echo \"✘ Error: Failed to configure g++-12.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    if ! python3 -m pip --version; then\n"
        "        echo \"✘ Error: Pip installation failed.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    echo \"✔ Installation completed successfully.\"\n"
        "}\n"
        "\n"
        "check_python3() {\n"
        "    PYTHON_PATH=$(which python3 | xargs dirname)\n"
        "    echo \"Found python3 at:\"$PYTHON_PATH\n"
        "    if [ \"$PYTHON_PATH\" == \"\" ]; then\n"
        "        echo \"✘ Python3 Path is not found.\"\n"
        "        exit 1\n"
        "    fi\n"
        "}\n"
        "\n"
        "setup_aidaptiv_package() {\n"
        "    mkdir -p /home/$deploy_usr/\n"
        "    mkdir -p /home/$deploy_usr/Desktop/\n"
        "    rm -rf /home/$deploy_usr/Desktop/dm /home/$deploy_usr/Desktop/aiDAPTIV2\n"
        "    mkdir /home/$deploy_usr/Desktop/dm /home/$deploy_usr/Desktop/aiDAPTIV2\n"
        "    TAR_NAME=\"vNXUN_2_01_00.tar\"\n"
        "    rm -f $TAR_NAME\n"
        "    if ! wget --tries=3 https://phisonbucket.s3.ap-northeast-1.amazonaws.com/$TAR_NAME --no-check-certificate; then\n"
        "        read -p \"✘ Can't get $TAR_NAME from cloud, Please enter the path to the $TAR_NAME file: \" filepath\n"
        "        tar xvf \"$filepath\" -C /home/$deploy_usr/Desktop/aiDAPTIV2\n"
        "    else\n"
        "        echo 'Get package from cloud'\n"
        "        tar xvf $TAR_NAME -C /home/$deploy_usr/Desktop/aiDAPTIV2\n"
        "    fi\n"
        "    echo 'unzip package'\n"
        "}\n"
        "\n"
        "appenvpath() {\n"
        "    case \":$PATH:\" in\n"
        "        *:\"$1\":*)\n"
        "            echo \"ENV path already exists in the PATH\"\n"
        "            ;;\n"
        "        *)\n"
        "            grep -qxF \"export PATH=\\\"/home/$USER/.local/bin:\$PATH\\\"\" \"/home/$deploy_usr/.bashrc\" || \\\n"
        "            echo \"export PATH=\\\"/home/$USER/.local/bin:\$PATH\\\"\" >> \"/home/$deploy_usr/.bashrc\"\n"
        "            ;;\n"
        "    esac\n"
        "    sudo -u $deploy_usr bash -c \"source /home/$deploy_usr/.bashrc\"\n"
        "}\n"
        "\n"
        "install_python_packages() {\n"
        "    PYTHON_PATH=$(which python3 | xargs dirname)\n"
        "    REQUIREMENTS_FILE=\"/home/$deploy_usr/Desktop/aiDAPTIV2/requirements.txt\"\n"
        "    if [[ ! -f $REQUIREMENTS_FILE ]]; then\n"
        "        echo \"✘ Error: requirements.txt file not found.\"\n"
        "        exit 1\n"
        "    fi\n"
        "    if [[ \"$deploy_usr\" != \"root\" ]]; then\n"
        "        echo \"Installing required packages for user $deploy_usr...\"\n"
        "        if ! sudo -u $deploy_usr pip install --user --force-reinstall -r \"$REQUIREMENTS_FILE\"; then\n"
        "            echo \"✘ Error: Failed to install required packages.\"\n"
        "            exit 1\n"
        "        fi\n"
        "        appenvpath /home/$deploy_usr/.local/bin\n"
        "    else\n"
        "        echo \"Installing required packages for root...\"\n"
        "        if ! pip install --force-reinstall -r \"$REQUIREMENTS_FILE\"; then\n"
        "            echo \"✘ Error: Failed to install required packages.\"\n"
        "            exit 1\n"
        "        fi\n"
        "    fi\n"
        "    echo \"✔ Successfully installed packages.\"\n"
        "}\n"
        "\n"
        "check_phisonai2() \n"
        "{\n"
        "    echo -e \"Validating phisonai2.....\"\n"
        "    is_available=0\n"
        "\n"
        "    # Check version for root\n"
        "    root_version=$(phisonai2 -v 2>/dev/null)\n"
        "    if [ $? -eq 0 ]; then\n"
        "        echo \"✔ phisonai2 is available for root.\"\n"
        "        echo \"phisonai2 version: $root_version\"\n"
        "        is_available=1\n"
        "        return\n"
        "    fi\n"
        "\n"
        "    # Check version for specified user\n"
        "    user_version=$(su - $deploy_usr -c 'phisonai2 -v 2>/dev/null')\n"
        "    if [ $? -eq 0 ]; then\n"
        "        echo \"✔ phisonai2 is available for user: $deploy_usr.\"\n"
        "        echo \"phisonai2 version: $user_version\"\n"
        "        is_available=1\n"
        "        return\n"
        "    fi\n"
        "\n"
        "    # Final check\n"
        "    if [ $is_available -eq 0 ]; then\n"
        "        echo \"✘ Error: phisonai2 is not available or functional for root or user: $deploy_usr.\"\n"
        "        echo \"Please ensure it is installed, functional, and added to the PATH.\"\n"
        "        exit 1\n"
        "    fi\n"
        "}\n"
        "\n"
        "deploy_aiDAPTIV()\n"
        "{\n"
        "    check_root\n"
        "    check_space 22G\n"
        "    select_install_user\n"
        "    install_drivers_and_cuda\n"
        "    install_other_apt_packages\n"
        "    check_python3\n"
        "    setup_aidaptiv_package\n"
        "    install_python_packages\n"
        "\n"
        "    cd /home/$deploy_usr/Desktop/aiDAPTIV2\n"
        "\n"
        "    sudo chmod +x bin/*\n"
        "    echo 'Edited bin permissions'\n"
        "    mv *.so ./phisonlib\n"
        "    sudo chmod +x ./phisonlib/ada.exe\n"
        "    sudo setcap cap_sys_admin,cap_dac_override=+eip ./phisonlib/ada.exe\n"
        "\n"
        "    PYTHON_PATH=$(which python3 | xargs dirname)\n"
        "\n"
        "    echo \"Setting up phisonai2.....\"\n"
        "    if [[ \"$PYTHON_PATH\" == \"/usr/bin\" && \"$deploy_usr\" != \"root\" ]]; then\n"
        "        cp bin/* /home/$deploy_usr/Desktop/dm/\n"
        "        mv bin/* /home/$deploy_usr/.local/bin/\n"
        "        rm -rf bin\n"
        "\n"
        "        rm -rf /home/$deploy_usr/.local/lib/python3.10/site-packages/phisonlib\n"
        "        mv phisonlib /home/$deploy_usr/.local/lib/python3.10/site-packages/\n"
        "        rm -rf phisonlib\n"
        "    else\n"
        "        cp bin/* /home/$deploy_usr/Desktop/dm/\n"
        "        mv bin/* $PYTHON_PATH\n"
        "        rm -rf bin\n"
        "\n"
        "        if [ \"$deploy_usr\" == \"root\" ] ; then\n"
        "            rm -rf /usr/local/lib/python3.10/dist-packages/phisonlib\n"
        "            mv phisonlib /usr/local/lib/python3.10/dist-packages\n"
        "            rm -rf phisonlib\n"
        "        else\n"
        "            rm -rf  $PYTHON_PATH/../lib/python3.10/site-packages/phisonlib\n"
        "            mv phisonlib $PYTHON_PATH/../lib/python3.10/site-packages/\n"
        "            rm -rf phisonlib\n"
        "        fi\n"
        "    fi\n"
        "\n"
        "    source ~/.bashrc\n"
        "    sudo -u $deploy_usr bash -c \"source /home/$deploy_usr/.bashrc\"\n"
        "    \n"
        "    check_phisonai2\n"
        "\n"
        "    echo '✔ Deploy Phison aiDAPTIV+ successfully..'\n"
        "}\n"
        "\n"
        "deploy_aiDAPTIV\n",
        NULL
    };

    execve("/bin/bash", args, environ);
    
    // If execve returns, it means there was an error
    perror("execve");
    return 1;
}